"""Layers this project does not carry.

Springs, soakages and sacred sites are out of scope unless the user asks for
them. Sacred site information in particular is culturally restricted and is not
something to publish into a portfolio atlas on the assumption that it would be
useful; the other two are simply not in the brief. Rather than rely on nobody
adding them by accident, `check_layer_names` refuses them at the point a layer
is written, and tests/test_scope_guard.py sweeps the repository as a backstop.

Lifting this is a one-line change to EXCLUDED_THEMES, and it should be made
deliberately when the user asks, not quietly.
"""

from __future__ import annotations

import re

EXCLUDED_THEMES: dict[str, tuple[str, ...]] = {
    "spring": ("spring", "springs"),
    "soakage": ("soak", "soaks", "soakage", "soakages"),
    "sacred": ("sacred", "sacredsite", "sacredsites"),
}

#: FME workspaces are not generated by this project.
EXCLUDED_EXTENSIONS = (".fmw", ".fmwt")


class ExcludedLayerError(Exception):
    """A layer was named that this project does not carry."""


def _tokens(name: str) -> set[str]:
    """Split on separators and on camelCase boundaries.

    Whole-token matching only. An earlier version also looked for the needles as
    substrings of the name with separators stripped, to catch spellings like
    `sacredsites` - but that flags `offspring_survey`, which contains `springs`.
    Splitting camelCase covers `SacredSite` without that false positive, and the
    genuinely concatenated spellings are listed explicitly instead.
    """
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)
    return {t for t in re.split(r"[^a-z0-9]+", spaced.lower()) if t}


def excluded_theme(name: str) -> str | None:
    """Return the theme `name` falls under, or None.

    Matching is on whole tokens so that ordinary words are not caught: a layer
    called `offspring_survey` or `springfield_rd` is not a springs layer.
    """
    tokens = _tokens(name)
    for theme, needles in EXCLUDED_THEMES.items():
        if tokens & set(needles):
            return theme
    return None


def check_layer_names(names) -> None:
    """Raise `ExcludedLayerError` if any name is an excluded theme."""
    offenders = [(n, excluded_theme(n)) for n in names if excluded_theme(n)]
    if offenders:
        detail = ", ".join(f"{n!r} ({theme})" for n, theme in offenders)
        raise ExcludedLayerError(
            f"Refusing to write layer(s) outside the agreed scope: {detail}. "
            f"Springs, soakages and sacred sites are excluded unless explicitly "
            f"requested; edit ntgw.scope.EXCLUDED_THEMES deliberately to change that."
        )
